# coding: utf-8
title: Pontepretano
email: raafael@tauil.com.br
description: > # this means to ignore newlines until "baseurl:"
  Noticias e Informações sobre a Associação Atlética Ponte Preta
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: pontepretano
github_username:  tauil

# Build settings
markdown: kramdown

sass:
  sass_dir: assets

menus:
  - text: 'História'
    href: '/historia'
  - text: 'Especial'
    href: '#'
    parents:
      - text: 'Campanha de 1969'
        href: '/campanha-de-1969'
      - text: 'Familia Burghi'
        href: '/familia-burghi'
      - text: 'derbi'
        href: '/derbi'
  - text: 'Equipe'
    href: '/equipe'
