# coding: utf-8
title: Pontepretano
email: raafael@tauil.com.br
description: > # this means to ignore newlines until "baseurl:"
  Noticias e Informações sobre a Associação Atlética Ponte Preta
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: pontepretano
github_username:  tauil
permalink: pretty
timezone: America/Sao_Paulo

# Build settings
markdown: kramdown

sass:
  sass_dir: assets

menus:
  - text: 'História'
    href: '/articles/pontepretano/2016/09/28/historia.html'
  - text: 'Especial'
    href: '#'
    parents:
      - text: 'Campanha de 1969'
        href: '/articles/pontepretano/2016/09/28/campanha-de-1969.html'
      - text: 'Familia Burghi'
        href: '/articles/pontepretano/2016/09/28/familia-burghi.html'
      - text: 'derbi'
        href: '/articles/pontepretano/2016/09/28/derbi-campineiro.html'
  - text: 'Equipe'
    href: '/equipe'
